FROM python:3.13-alpine

WORKDIR /backend

COPY ./requirements/prod.txt /backend/requirements/prod.txt
RUN pip install --no-cache-dir --upgrade -r /backend/requirements/prod.txt

COPY ./src /backend/src
COPY alembic.ini /backend/alembic.ini
COPY ./alembic /backend/alembic

CMD alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload