services:
    app:
        container_name: app
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_started

    db:
        container_name: db
        restart: always
        image: postgres:14.4-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${USER}
            POSTGRES_PASSWORD: ${PASSWORD}
            POSTGRES_DB: ${NAME}
        env_file:
             - .env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 2s
            timeout: 5s
            retries: 10
        volumes:
            - postgres_data:/data

    redis:
        container_name: redis
        image: redis:7-alpine
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 60 1 --loglevel warning
        volumes:
            - redis_data:/data

volumes:
    redis_data:
    postgres_data:
