"""drop trade_user relations

Revision ID: f8e04f7f22ff
Revises: 31b9abc0b393
Create Date: 2025-03-18 21:05:27.903777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e04f7f22ff'
down_revision: Union[str, None] = '31b9abc0b393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade', 'seller',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('trade_seller_fkey', 'trade', type_='foreignkey')
    op.drop_constraint('trade_buyer_fkey', 'trade', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('trade_buyer_fkey', 'trade', 'user', ['buyer'], ['id'])
    op.create_foreign_key('trade_seller_fkey', 'trade', 'user', ['seller'], ['id'])
    op.alter_column('trade', 'seller',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
