"""return relations in trade table

Revision ID: 4d84c29a9e79
Revises: f8e27d819d84
Create Date: 2025-03-18 21:09:25.231258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d84c29a9e79'
down_revision: Union[str, None] = 'f8e27d819d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade', 'seller',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'trade', 'users', ['seller'], ['id'])
    op.create_foreign_key(None, 'trade', 'users', ['buyer'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trade', type_='foreignkey')
    op.drop_constraint(None, 'trade', type_='foreignkey')
    op.alter_column('trade', 'seller',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
