"""alter_nullable_columns

Revision ID: 089edfb00026
Revises: 4d84c29a9e79
Create Date: 2025-03-28 21:28:25.389012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089edfb00026'
down_revision: Union[str, None] = '4d84c29a9e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'id_trade',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('service', 'id_trade',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'id_subscription',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id_subscription',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('service', 'id_trade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('item', 'id_trade',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
