"""add relations

Revision ID: 31b9abc0b393
Revises: 138afe722e92
Create Date: 2025-03-08 13:04:33.445295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b9abc0b393'
down_revision: Union[str, None] = '138afe722e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'id_trade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'item', 'trade', ['id_trade'], ['id'])
    op.alter_column('service', 'id_trade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'service', 'trade', ['id_trade'], ['id'])
    op.alter_column('subscription', 'id_subscription_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'subscription', 'subscription_type', ['id_subscription_type'], ['id'])
    op.alter_column('trade', 'seller',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'trade', 'user', ['seller'], ['id'])
    op.create_foreign_key(None, 'trade', 'user', ['buyer'], ['id'])
    op.alter_column('user', 'id_subscription',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['id_subscription'])
    op.create_foreign_key('fk_user_subscription', 'user', 'subscription', ['id_subscription'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_subscription', 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'id_subscription',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'trade', type_='foreignkey')
    op.drop_constraint(None, 'trade', type_='foreignkey')
    op.alter_column('trade', 'seller',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.alter_column('subscription', 'id_subscription_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.alter_column('service', 'id_trade',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.alter_column('item', 'id_trade',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
